Update bitshiftRight.adoc
arduino/reference-pt pull request #524
Opened 2021-06-17 22:04 UTC by apenas1ignorante

fixing some little mistakes

2021-06-17 22:41 UTC, per1234 requested changes

2021-06-17 22:41 UTC, per1234 commented on Language/Structure/Bitwise Operators/bitshiftRight.adoc
> +int resultado = (unsigned int) x >> y;  // binário: 0001111111111110
```suggestion
int resultado = (unsigned int)x >> y;  // binário: 0001111111111110
```
This one is correct as it is:
https://www.arduino.cc/reference/en/language/variables/conversion/unsignedintcast/#_syntax

2021-06-17 23:14 UTC, apenas1ignorante commented
sorry, i'm new to arduino (started reading the documentation a few days
ago) but thanks for letting me know.

>

2021-11-25 02:34 UTC, per1234 approved these changes

2021-11-25 02:34 UTC, merged